---
- name: Setup docker
  tags: base
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install prerequirements
      yum: name="{{ item }}" state=installed
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: Setup docker repo
      yum_repository:
        name: docker
        description: docker-ee
        baseurl: "{{ docker_url }}/centos/$releasever/$basearch/stable/"
        gpgkey: "{{ docker_url }}/gpg"
        gpgcheck: yes
    - name: Install docker-ee
      yum: name="{{ item }}" state=installed
      with_items:
        - docker-ee
    - name: Start and enable docker-ee
      service: name=docker state=started enabled=yes

- name: Setup UCP
  tags: ucp
  hosts: controllers
  become: true
  become_method: sudo
  become_user: root
  vars:
    ucp_version: latest
    admin_username: admin
    admin_password: admin123

  tasks:
    - name: Check if UCP is running
      changed_when: false
      register: ucp_running
      command: docker ps --filter "name=ucp-swarm-manager" --format '{{ '{{' }}.Names{{ '}}' }}'

    - name: Install UCP
      when: 'not "ucp-swarm-manager" in ucp_running.stdout_lines'
      shell: docker container run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:2.2.6 install --host-address {{ ansible_default_ipv4['address'] }} --san controller1.docker.lab --san worker1.docker.lab --san worker2.docker.lab --san controller1 --san worker1 --san worker2 --admin-username {{ admin_username }} --admin_password {{ admin_password }} --disable-tracking --disable-usage --security-opt label=disable
      register: install_ucp

    - name: UCP is installed
      when: '"ucp-swarm-manager" in ucp_running.stdout_lines'
      debug: msg='To uninstall UCP, run docker container run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/ucp:{{ ucp_version }} uninstall-ucp'

    - name: Output UCP installation
      when: install_ucp.stderr is defined
      debug: var=install_ucp.stderr_lines
