---
- name: Setup machine
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Add ssh keys to authorized_keys
      lineinfile:
        dest: "/home/{{ item }}/.ssh/authorized_keys"
        state: present
        create: yes
        line: "{{ public_key }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0644
      with_items:
        - vagrant
