---
- name: Setup machine
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install prerequirements
      yum: name="{{ item }}" state=installed
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - epel-release
        - kubernetes-client
    - name: Install packages from epel
      yum: name="{{ item }}" state=installed update_cache=yes
      with_items:
        - jq
    - name: Setup docker repo
      yum_repository:
        name: docker
        description: docker-ee
        baseurl: "{{ docker_url }}/centos/$releasever/$basearch/stable/"
        gpgkey: "{{ docker_url }}/gpg"
        gpgcheck: yes
    - name: Disable swap
      command: swapoff -a
    - name: Comment out swap from fstab
      command: sed -i -e 's~\(.*swap.*\)~#\1~g' /etc/fstab
    - name: Install docker-ee
      yum: name="{{ item }}" state=installed
      with_items:
        - docker-ee
    - name: Start and enable docker-ee
      service: name=docker state=started enabled=yes

    - name: Add ssh keys to authorized_keys
      lineinfile:
        dest: "/home/{{ item }}/.ssh/authorized_keys"
        state: present
        create: yes
        line: "{{ public_key }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0644
      with_items:
        - vagrant
    - name: Add vagrant to docker group
      user:
        append: yes
        groups: docker
        name: vagrant

