---
- name: Setup docker
  tags: base
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Install prerequirements
      yum: name="{{ item }}" state=installed
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: Setup docker repo
      yum_repository:
        name: docker
        description: docker-ee
        baseurl: "{{ docker_url }}/centos/$releasever/$basearch/stable/"
        gpgkey: "{{ docker_url }}/gpg"
        gpgcheck: yes
    - name: Install docker-ee
      yum: name="{{ item }}" state=installed
      with_items:
        - docker-ee
    - name: Start and enable docker-ee
      service: name=docker state=started enabled=yes

- name: Setup DTR
  tags: ucp
  hosts: controllers
  become: true
  become_method: sudo
  become_user: root
  vars:
    dtr_version: latest
    replica_http_port: 81
    replica_https_port: 444
    ucp_node: controller1
    ucp_password: admin123
    ucp_username: admin
    ucp_url: https://192.168.11.21
  tasks:
    - name: Check if DTR is running
      changed_when: false
      check_mode: no
      register: dtr_running
      command: docker ps --filter "name=dtr" --format '{{ '{{' }}.Image{{ '}}' }}'

    - name: Install DTR
      when: 'not "docker/dtr-nginx:2.5.0" in dtr_running.stdout_lines'
      shell: docker container run --rm docker/dtr install  --ucp-node {{ ucp_node }} --ucp-username {{ ucp_username }}   --ucp-url {{ ucp_url }}  --ucp-insecure-tls --ucp-password {{ ucp_password }} --replica-http-port {{ replica_http_port }} --replica-https-port {{ replica_https_port }}
      register: install_ucp

    - name: DTR is installed
      when: '"docker/dtr-nginx:2.5.0" in dtr_running.stdout_lines'
      debug: msg='To uninstall UCP, run docker container run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock docker/dtr:{{ dtr_version }} remove'

    - name: Output UCP installation
      when: install_ucp.stderr is defined
      debug: var=install_ucp.stderr_lines
