version: '3'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    healthcheck:
      interval: 10m
    deploy:
      labels:
        - com.docker.lb.hosts=gitlab.docker.lab
        - com.docker.lb.port=80
    restart: on-failure
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.11.21'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
#    ports:
#      - 22
#       - 80
#       - 443
    volumes:
      - gitlab_etc:/etc/gitlab
      - gitlab_log:/var/log/gitlab
      - gitlab_opt:/var/opt/gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - gitlab_runner-etc:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  gitlab_etc:
  gitlab_log:
  gitlab_opt:
  gitlab_runner-etc:
