version: '3'
services:
  gitea:
    deploy:
      placement:
        constraints:
          #          - "engine.labels.jenkins == master"
          - node.hostname == worker1
    image: gitea/gitea:1.4
    volumes:
      - gitea_data:/data
    ports:
      - 2222:22
      - 3000:3000
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10
    deploy:
      placement:
        constraints:
          #- "engine.labels.jenkins == master"
          - node.hostname == worker1
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    volumes:
      - mariadb_data:/var/lib/mysql
  jenkins:
    image: jenkins:latest
    deploy:
      placement:
        constraints:
          #- "engine.labels.jenkins == master"
          - node.hostname == worker1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
  gitea_data:
  mariadb_data:
